### ISSUE TITLE
Render Context? 

### ISSUE THREAD

**Issue by arpowers** [vueuse/head#11]
The new library looks great. Sorely needed. 

From looking at the docs, there is nothing mentioned about providing the context (e.g. the route `url`) for the rendering. 

I know that `renderToString` supports a second context argument: 

```js 
const HTML = renderToString(app, {url: '/whatever'})
```

How does the SSR code address this?

**Comment by antfu** [comment]
You would need to navigate the path via your router, you might need to read the SSR docs. I think there it's not related to this package.

Here is an example: https://github.com/vuejs/vitepress/blob/8cd0023176793783315cfa5d9999788f53fe32d4/src/node/build/render.ts#L23-L25

**Comment by arpowers** [comment]
You could do that, although that's what is considered the `magical` approach and isn't a best practice since it requires throwing around globals (loss of cause/effect)

Generally you'd want to support explicit context and possibly fall back to global based inferrance.

**Comment by egoist** [comment]
that's out of the scope, I don't think it has anything to do with head management.

**Comment by arpowers** [comment]
As you need to account for route anyway (using magic) I don't see why it would be a challenge to implement this. Anyway, I've yet to dig into the library and just was curious how this was handled. 

For additional insight, here is how we currently handle SSR with Vue3/Vite

```js 
if (render == RenderMode.SSR) {
    const { factorApp } = require(serverOutput)
    const context = { url: cxt.url }
    const fa: VueApp = await factorApp(context)
    const content = await renderToString(fa, context)
    html = html.replace(
      '<div id="app"></div>',
      `<div id="app" data-server-rendered="true">${content}</div>`,
    )
  }
```

Notice that since we set the URL context, we don't need to deal with the router as the URL is passed in via the Koa middleware and can be passed directly .
