### ISSUE TITLE
Isnt updating tags.

### ISSUE THREAD

**Issue by Milo123459** [vueuse/head#12]
Hi, I'm using vue-class-component and I have this:

@Options({
  components: {
    HomeComponent,
  },  
  setup() {
      useHead(() => ({
      title: `Spencer: Home`,
      meta: [
        {
          name: `description`,
          content: `hey`,
        },
      ],
      
    }))
  }
})
export default class Home extends Vue {}

But, the title isn't changing. Any ideas? Embeds don't work either

**Comment by egoist** [comment]
Please properly format the issue content and provide a repro using CodeSandbox.io

**Comment by Milo123459** [comment]
Can I just give you the repo https://github.com/Milo123459/spencer-web and the production: https://spencer-one.vercel.app

**Comment by egoist** [comment]
Not sure how vue-class-component v8 works and there are no docs, most likely it's not related to this project and you should probably file an issue there instead.
