### ISSUE TITLE
Head component does not work in vue 2.7

### ISSUE THREAD

**Issue by vetruvet** [vueuse/head#146]
`<Head>...</Head>` does not do anything in vue 2.7.

[Reproduction link](https://codesandbox.io/s/gracious-silence-4b9h00?file=/src/HelloWorld.vue)

Expected Results: 2 `<meta>` tags (`use-foo` and `component-foo`)
Actual Results: 1 `<meta>` tag (`use-foo`)

At first glance, it seems that `<Head>` is targeting the vue 3 VNode API and is not compatible with the vue 2 VNode API.

**Comment by harlan-zw** [comment]
Hey @vetruvet 

Thanks for the reproduction. 

I'll need to dig into the differences in how the node VNode API's work between v2 and v3. This issue will be low priority though given this package is mainly targeted at v3. 

If you really need it over `useHead`, a PR would be appreciated :)
