### ISSUE TITLE
"Deleting" a tag

### ISSUE THREAD

**Issue by manniL** [vueuse/head#152]
Hey 👋🏻

I was wondering if it is possible to "delete" a tag by setting nothing except the `key`, e.g.: `link: [{ key: 'favicon' }]`. This could be useful to override tags in child components but right now just renders an empty `<link>` tag.

**Comment by harlan-zw** [comment]
This makes perfect sense, we shouldn't be rendering empty tags. 

I'm in the middle of a pretty massive refactor but will make sure this finds itself in there

**Comment by harlan-zw** [comment]
This is available in the latest v1. You can find documentation here: https://unhead.harlanzw.com/guide/guides/handling-duplicates#removing-a-nested-tag
