### ISSUE TITLE
Title is not in the html file when using `nuxi generate`

### ISSUE THREAD

**Issue by DaniGTA** [vueuse/head#155]
When i set the head via 
```vue
    <Head>
      <Title>Test</Title>
    </Head>
```
or
```vue
<script setup lang="ts">
const { t } = useI18n();
useHead({
  title: "test",
});
</script>
```

the generated html file via `nuxi generate` has no title.
When the user opens the html file it shows the correct title. but isnt this bad for bots? When they dont render js they cant grab the title.

**Comment by harlan-zw** [comment]
Hey @DaniGTA 

Are you generating as a SPA? If so this is a known issue and will be fixed soon

**Comment by harlan-zw** [comment]
Should be fixed in the edge channel https://github.com/nuxt/framework/pull/8975/files
