### ISSUE TITLE
Types: `key` shouldn't undefined for `link` entries

### ISSUE THREAD

**Issue by manniL** [vueuse/head#158]
Reproduction code:

```
<script setup lang="ts">
useHead({
  link: [{ rel: 'icon', key: 'favicon', href: 'SOME_STRING' }],
});
</script>
<template>
  <div>
    <h1>Hi</h1>
  </div>
</template>
```

Expected: key should be fine as `string` or ref/computed/... returning one

Actual:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/640208/201071121-c0f4a477-3176-4ec6-b97c-dc789093d323.png">

**Comment by harlan-zw** [comment]
Thanks for the issue. This was legacy logic around key handling, for some reason links were excluded and I wasn't prepared to break anything to allow them.

This is fixed in v1, I'll leave this open until it's officially released

**Comment by harlan-zw** [comment]
v1 looking good, going to close this off

![image](https://user-images.githubusercontent.com/5326365/201589387-27f16a95-8e1e-4fb8-add1-8484cbe1385e.png)
