### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by rudolfbyker** [vueuse/head#160]
I see there is some good work being done on Vue 2.7 compatibility (which I also need) at https://github.com/vueuse/head/tree/vue27-compatibility .

However, the README on the master branch touts 2.7 compatibility already, but this branch https://github.com/vueuse/head/tree/vue27-compatibility is not merged yet.

Is there a plan for when this will be released?

Is there a release road map in general?

**Comment by rudolfbyker** [comment]
Ah, I just discovered the pre-releases of version `1.y.z`. That helps.

Yet my question is about release planning in general :)

**Comment by harlan-zw** [comment]
Hey @rudolfbyker 

Thanks for the issue. I'm currently working fast on a v1 stable release, given the internal API and features were changing day by day I wanted to avoid documenting anything official until the development was finished.

With that in mind though, I've just pushed out a new v1.0.0-next.1, which is on the https://github.com/vueuse/head/tree/v1 branch. This is tested to work with Vue 2 and you can try it now (docs on the v1 branch should work).

Expect to see a proper migration guide within the week

**Comment by harlan-zw** [comment]
See v1 announcement :)
