### ISSUE TITLE
head.addEntry is not a function

### ISSUE THREAD

**Issue by umarmalikofficial** [vueuse/head#163]
I have installed Nuxt JS app using `npx nuxi init nuxt-app`

But it gives an error on `npm run dev` as below:

[Vue warn]: Unhandled error during execution of setup function 
  at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="head.addEntry is not a function"  ... >
[nuxt] [request error] [unhandled] [500] head.addEntry is not a function
  at ./node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin.mjs:11:8
  
  
  Note: I commented out the `head.addEntry()` function call so it's working on my side now.

**Comment by PhoneBuster** [comment]
I am not shure, but addEntry(...) should be addHeadObjs(...) instead. After renaming it works.

**Comment by harlan-zw** [comment]
Hey there, please wait for the official nuxt integration. It will likely be out tomorrow

**Comment by harlan-zw** [comment]
Sorry, I misunderstood this initially, it relates to https://github.com/nuxt/framework/issues/8936

The issue should be fixed, let me know if you have any issues

**Comment by umarmalikofficial** [comment]
@harlan-zw, it has been resolved now. 

Thanks, Brother!
