### ISSUE TITLE
Duplicate keyed tags being generated between pages (@vueuse/schema-org)

### ISSUE THREAD

**Issue by AleksejDix** [vueuse/head#164]
looks like https://vue-schema-org.netlify.app/ relies on the old version of the plugin. 

Your help might be needed to make Schema work with new Version

**Comment by harlan-zw** [comment]
Hey @AleksejDix 

This may be fixed, can you try upgrading @vueuse/schema-org to [v1.1.0-beta.6](https://github.com/vueuse/schema-org/releases/tag/v1.1.0-beta.6)

**Comment by AleksejDix** [comment]
@harlan-zw  after upgrade to https://github.com/vueuse/schema-org/releases/tag/v1.1.0-beta.6 

ld+json blocks display content, but there are multiple blocks at the same time 

<img width="746" alt="Bildschirmfoto 2022-11-13 um 16 49 20" src="https://user-images.githubusercontent.com/8349161/201530882-844ccda3-ab5b-4b2f-9871-adb45a0b2b2b.png">

**Comment by harlan-zw** [comment]
Thanks for flagging this @AleksejDix 

The duplicate tag being created is fixed in the latest version (1.0.7) as far as I can tell, let me know if you still have any issues :)

**Comment by AleksejDix** [comment]
Waiting for 1.07 to be released :D  then i can confirm the fix 

Great work! 

Thx for making those changes so quickly.

**Comment by harlan-zw** [comment]
Thanks :) 

Should be out and ready to go, in fact, I'm up to 1.0.10 now :laughing:

**Comment by AleksejDix** [comment]
There are still Issues

Issue 1 
Demo: https://schema-json-lg.pr.propertycaptain.ch/en/faq

FAQ 
`    <SchemaOrgQuestion
      v-for="faq in meataQuestions"
      :key="faq.id + language"
      :name="faq.question"
      :accepted-answer="faq.answer"
    >
    </SchemaOrgQuestion>
`

Question are not getting removed after navigation to AboutUs page 
Also Question Do not change when Language of the site is changes - Language is changes based on route aliases.



Issue 2 

if Title is empty no fallback from TitleTemplate function is shown.
`<title>` tag is missing completely on this pages

**Comment by harlan-zw** [comment]
I believe the reactivity issues are issues with @vueuse/schema-org itself, I'll look into it soon once @vueuse/head is stable. Reactivity isn't a major issue anyway though, it's only meant to be implemented in dev because in production only the initial schema-org will be used.

For issue 2 would you mind providing an example? Is this specific to the schema-org or @vueuse/head

Feel free to contact me on discord if you want to debug it togethor
