### ISSUE TITLE
How to get type of script from useHead()?

### ISSUE THREAD

**Issue by nestle49** [vueuse/head#170]
How to get type of script from useHead()?

**Comment by harlan-zw** [comment]
Hi @nestle49 

Would you further explaining what you mean, maybe with a code example as well?

**Comment by nestle49** [comment]
Before with vue-meta used MetaInfo['script'], now i used Script, but I'm force need 'as' syntax
```
// eslint-disable-next-line import/no-extraneous-dependencies
import { Script } from '@unhead/schema';
```

`const scripts: Script[] = [];`

```
scripts.push({
                innerHTML: [
                    `bodyScript`
                ]
                    .filter(notEmpty)
                    .join('\n')
            } as Script);
```

```
useHead({
    script: [...scripts],
    link: []
});
```

**Comment by harlan-zw** [comment]
Try something like this

```ts
import type { ReactiveHead } from '@unhead/vue'

const script: ReactiveHead['script'] = [];

script.push({
  src: 'https://unpkg.com/@unhead/vue@latest/dist/vue.esm-browser.js',
  defer: true
})

useHead({
  script,
})
```

**Comment by harlan-zw** [comment]
That's because `callback` isn't a valid field, neither is `json`. You should refer to the docs, specifically the DOM events if you need some behaviour similar to callback

https://unhead.harlanzw.com/guide/guides/dom-event-handling
