### ISSUE TITLE
change icon not work

### ISSUE THREAD

**Issue by callmesoul** [vueuse/head#178]
```
useHead({
      title: 'Open-sourced',
      meta: [
        {
          name: 'description',
          content:
            'Open-sourced',
        },
        {
          name: 'keywords',
          content: 'Open-sourced',
        },
      ],
      link: [
        {
          rel: 'icon',
          key: 'favicon',
          href: '/name.ico',
        },
      ],
    })
```

It haved two  `<link rel="icon" key="favicon" href="...">`

env:
vue3.2
"vite": "3.1.3",

**Comment by harlan-zw** [comment]
Hey @callmesoul 

Please refer to the docs https://unhead.harlanzw.com/guide/guides/handling-duplicates#providing-a-key

Let me know if it's not clear

**Comment by callmesoul** [comment]
@harlan-zw when index.html init haved   `<link rel="icon" key="favicon" href="...">` is awalys haved two

index.html
```
<link rel="icon" key="favicon" href="/favicon.ico" />
```
useHead({
      link: [
        {
          rel: 'icon',
          key: 'favicon',
          href: '/name.ico',
        },
      ],
    })
```

```

**Comment by harlan-zw** [comment]
This isn't really supported as there's no native html `key`. There's a dedupe attribute `data-h-${hash}` which you could use if you can modify the HTML.

Ideally, you just let either the initial html handle the favicon or you have unhead do it all.
