### ISSUE TITLE
Noscript still seems to not be working

### ISSUE THREAD

**Issue by andreMariano90** [vueuse/head#180]
Implementing the noscript as commented [here](https://github.com/vueuse/head/issues/84) does not seem to be loading the iframe properly

Loading on the standard way, we can see the source and the network requesting the content

![standard_html](https://user-images.githubusercontent.com/1918494/218584015-7471a3d8-69ed-41c4-a459-3ce5391efadb.png)

![standard_network](https://user-images.githubusercontent.com/1918494/218584022-8cec689f-1c91-46f6-afc1-5da41951202f.png)

![standard_source](https://user-images.githubusercontent.com/1918494/218584018-e43cd521-e82a-4a19-86b6-5c5c36b3d2e4.png)

When using the:
```
useHead({
        noscript: [
          {
            children: `<iframe src="https://www.googletagmanager.com/ns.html?${serialize(params)}" height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
            tagPosition: 'bodyOpen'
          }
        ]
      })
```

Besides seeing the iframe being loaded as a string, we don't see any network activity at all

![usehead_html](https://user-images.githubusercontent.com/1918494/218584343-1e551935-a691-4056-94a1-cdac8e035284.png)

![usehead_network](https://user-images.githubusercontent.com/1918494/218584340-fa8bec86-bc40-4af4-8db2-a6bbfd58282c.png)

![usehead_source](https://user-images.githubusercontent.com/1918494/218584342-aaa24103-4fab-4f0f-9dc7-bf821e2c4908.png)

I have added a stackblitz to show this is not working properly.
I'm loading both iframes, but I can only find the first one as a real element
https://stackblitz.com/edit/nuxt-starter-v3etsl?file=app.vue

**Comment by harlan-zw** [comment]
I tried your reproduction, it looks like it loads correctly when you disable javascript?

![image](https://user-images.githubusercontent.com/5326365/219001494-8bfc8302-a8bc-4002-85c2-c0b6b3653eb0.png)

Not sure why you're trying to test it using scripts :upside_down_face:. If you can provide a reproduction where it doesn't work with scripts disable I'm happy to investigate
