### ISSUE TITLE
Optional chaining are not compiled to ES5

### ISSUE THREAD

**Issue by BlackCubeNo99** [vueuse/head#184]
Product code "$el?.remove()" reports an error in older browsers

![image](https://user-images.githubusercontent.com/38855282/231767392-35704fff-4890-42df-b5da-e48e52ee2f46.png)

**Comment by harlan-zw** [comment]
Hey @BlackCubeNo99, if you'd like to support non-modern browsers you should transpile the `@unhead/dom` package. 

I could fix this one issue but can't guarantee new ES5 errors won't be introduced.

If you provide some details about your build setup I can guide you on how to do that if you don't know how.

**Comment by code-lixm** [comment]
same problem for me
