### ISSUE TITLE
@vueuse/head not working properly with vite-plugin-ssr in SSR mode

### ISSUE THREAD

**Issue by SquirrelCoder** [vueuse/head#185]
Hi,
first of all, thank you very much for your hard work.

The issue mentioned here: https://github.com/vueuse/head/issues/24 still persists.

I have created a sample repository to show the problem.

https://github.com/SquirrelCoder/vite-plugin-ssr-vueuse-head

The tags are set correctly when in CSR mode but in SSR the tags are not there.

Could you please have a look at this issue? 

Thanks a lot.

Tagging also @brillout

**Comment by harlan-zw** [comment]
Hey @SquirrelCoder, thanks for the issue.

I've looked at the repo and it looks like an issue with your setup. You are creating a new head instance after the tags have been rendered in _default.page.server.ts.

```ts
const appHtml = await renderToString(app);
const head = createHead(); // this is going to reset all collected head data
const { headTags, htmlAttrs, bodyAttrs, bodyTags } = await renderHeadToString(head);
```

If you need the head instance you should either create it exclusively in this file or you can return it from `createApp`.

```ts
  const { app, head } = createApp(Page, pageProps, pageContext);
  const appHtml = await renderToString(app);
  const { headTags, htmlAttrs, bodyAttrs, bodyTags } = await renderHeadToString(head);
```

Let me know if any of that isn't clear.

**Comment by SquirrelCoder** [comment]
oh shoot, I'm sorry, yeah that makes total sense. Thanks a lot.

**Comment by anatoliidaostreet** [comment]
Hey @harlan-zw 
I do how you propose, but i am getting sting of metadata in the body tag
```javascript
const { app, head } = createApp(pageContext);
const pageHtml = pageContext.Page ? await renderToString(app) : '';
const { headTags, htmlAttrs, bodyTags } = await renderSSRHead(head);
```

![Screenshot 2023-05-18 at 15 37 08](https://github.com/vueuse/head/assets/123463263/56a08094-96d3-4003-8a8f-3d31efcfa8c1)

Did I miss something?

I use
`vue3, vite-plugin-ssr with ssr and spa mode together`

**Comment by SquirrelCoder** [comment]
@anatoliidaostreet That's not a problem with vueuse. I have asked the same question here: https://github.com/brillout/vite-plugin-ssr/issues/865.
You have to use it like this:

```
const documentHtml = escapeInject`<!DOCTYPE html>
    <html>
      <head>
      ${ dangerouslySkipEscape(headTags) }
    </head>
      <body>
        <div id="app">${ stringApp }</div>
      </body>
    </html>`;
```

**Comment by brillout** [comment]
FYI the next vite-plugin-ssr version will warn the user when this happens.

**Comment by harlan-zw** [comment]
Amazing, thanks @brillout
