### ISSUE TITLE
The installation guide link is pointing to a broken link

### ISSUE THREAD

**Issue by rezelute** [vueuse/head#189]
![image](https://github.com/vueuse/head/assets/13378850/7cdc3998-83b4-4152-a70f-3566e03fb77e)
The link that's broken is: https://unhead.unjs.io/integrations/vue/setup

**Comment by harlan-zw** [comment]
Thanks, have fixed that up and the repo site link :)

**Comment by rezelute** [comment]
Beaaautiful, thanks for the quick update 🛩️
