### ISSUE TITLE
Support structure data ld+json scripts

### ISSUE THREAD

**Issue by frandiox** [vueuse/head#21]
Currently, a script gets its content rendered as attributes. It would be useful to render its "content" prop as children instead in order to support [ld+json](https://developers.google.com/search/docs/guides/intro-structured-data).

**Comment by egoist** [comment]
You can use `children` property instead, but yeah I think it's good to add `content` too since vue-meta is using it too.

**Comment by harlan-zw** [comment]
Given that most people have adopted this package using the `children` prop, I don't think it's worth creating an alias prop of `content`. 

Will close this off, but feel free to re-open if you think it's important.
