### ISSUE TITLE
Can I remove the `data-XXX` attributes?

### ISSUE THREAD

**Issue by yaquawa** [vueuse/head#23]
I saw some extra `data-XX` attributes was generated via `renderHeadToString`:

```html
<html class='home-page' data-head-attrs='class'>
<head>
  <title>home page</title>
  <meta name='head:count' content='0'>
</head>
<body class='home-page-body' data-head-attrs='class'>
<div id='app'>
  <div>hi
    <main>world</main>
  </div>
</div>
</body>
</html>
```
in this example: `data-head-attrs`,`<meta name='head:count' content='0'>`

what's the purpose of this? Can I remove them?

**Comment by egoist** [comment]
No, they're used internally to determine which attributes are added by vue-use-head

**Comment by glen-84** [comment]
It's a bit strange to surface this in the DOM. Couldn't that data be stored on an [expando](https://developer.mozilla.org/en-US/docs/Glossary/Expando), or in vueuse/head's own state?
