### ISSUE TITLE
@vueuse/head not working properly with vite-plugin-ssr

### ISSUE THREAD

**Issue by ozergul** [vueuse/head#24]
Hello thanks for this plugin. I wanna use this with [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) and tried something simple. As I see <title> is not created in server side.

Here are the example:
I cloned https://github.com/brillout/vite-plugin-ssr/tree/master/examples/vue-router and added @vueuse/head
https://github.com/ozergul/vite-ssr-usehead

What can be done?

**Comment by brillout** [comment]
I had a look at https://github.com/ozergul/vite-ssr-usehead and everything works as expected with the exception that `@vueuse/head` doesn't collect the head meta data on SSR. AFAICT this is a `@vueuse/head` prob and not a `vite-plugin-ssr` one.

**Comment by harlan-zw** [comment]
This issue is quite old so going to close.

If you'd still like help with this please re-open

**Comment by SquirrelCoder** [comment]
I think this issue still persists and the heads could not be set when in SSR mode. 
I have created a sample repository to show the problem.

https://github.com/SquirrelCoder/vite-plugin-ssr-vueuse-head

The tags are set correctly when in CSR mode but in SSR the tags are not there.
Could you please have a look at this issue?

Thanks a lot.
