### ISSUE TITLE
make API better

### ISSUE THREAD

**Issue by dongnaebi** [vueuse/head#31]
Most of the time, we set page title after async fetch, so we must use computed:
```javascript
title: computed(() => siteData.title)
```
why not provide a function to set the reactive object? like this:
```javascript
import { useHead } from '@vueuse/head'
export default defineComponent({
  async setup() {
    const setHead = useHead()

    setHead({
      title: 'static string',
      meta: [
        {
          name: 'description',
          content: 'static string',
        },
      ],
    })
  },
})
```
And most of the time, we must set title, description and keywords for SEO, so I think we can make it more convenient:
```javascript
setHead({
  title: 'static string',
  description: 'static string',
  keywords: 'static keywords',
  meta: [
    // ...
  ],
  script: [
    // ...
  ]
})
```

**Comment by harlan-zw** [comment]
Within the new v1 RCs reactivity is vastly improved.

For item 1, just pass in a ref as the object and modify it whenever you need.

```ts
const head : Ref<HeadObjectPlain> = ref({})

useHead(head)

head.value.title =  `Hello world: ${version}`
head.value.meta = [
  { name: 'description', content: 'This is an example' },
  { property: 'og:title', content: 'Hello world' },
]
```

For item 2, you can use the `unpackMeta` util from [zhead](https://github.com/harlan-zw/zhead#unpackmeta).

It may make itself into a feature of @vueuse/head as some point, but for now you can import it

```ts
import { unpackMeta } from 'zhead'
import { useHead } from '@vueuse/head'

useHead({
  title: 'static string',
  meta: unpackMeta({
    description: 'static string',
    keywords: 'static keywords',
  }),
  script: [
    // ...
  ]
})
```

Let me know your thoughts on those and if you think any additional API changes are needed.
