### ISSUE TITLE
ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by Uninen** [vueuse/head#34]
I'm using `@vueuse/head` v0.6.0 with `vite-ssg` and was confused with the following error message that killed the build script because it refers to Node (which I thought meant the language but actually refers to a variable called Node in this case).

```
ReferenceError: Node is not defined
    at /[..]/node_modules/@vueuse/head/dist/index.js:202:55
    at Array.forEach (<anonymous>)
```

The following code in the built script in dist is the culprit:

```js
  oldElements.forEach((el) => {
    if (el.nextSibling && el.nextSibling.nodeType === Node.TEXT_NODE) {
      el.nextSibling.remove();
    }
    el.remove();
  });
```

There is no `Node.TEXT_NODE` imported or defined anywhere so if run this code will fail (although it seems to work fine in the browser at least w/ Vite dev server). This was introduced in #28. My workaround is to use npm version 0.5.1 which works fine, the current 0.6.0 doesn't.

**Comment by praburangki** [comment]
@Uninen I had the same issue, then I upgraded my nodejs version into `16.4.0` and it works. Not sure what was the issue.

**Comment by praburangki** [comment]
So after a few trial and errors i've manage it pass the build step. In the `index.html` I have this line:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

And in the `useHead` within the `meta` arrays there is this code:

```
{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
```

After I removed it from the array then the build pass.

**Comment by usercao** [comment]
The main problem is that the custom `head` cannot duplicate the `index.html`

**Comment by ebisbe** [comment]
The solution from what @usercao said is to remove all `<meta>` tags from the `index.html` and handle those default tags directly in the code. 
@praburangki that's working under the `node -v v14.18.0`
