### ISSUE TITLE
Dynamic title component memory leak

### ISSUE THREAD

**Issue by petrck** [vueuse/head#36]
I found something special in using dynamic reference title in template component. Look at this:

```
<template>
       <div>
            <Head>
                <title> {{ somethingComputedObject.prop }} </title>
            </Head>
            
            .....
            
       </div>
</template>

....

```

The server monitor show memory leaks in apache benchmark test. Works fine without Head component, or with static text (not reference property). Composition API hook looks well too - I've analyzed problem only in component.

Can you check it please? Thank you.

**Comment by harlan-zw** [comment]
I believe this is fixed within the v1 RC's, please re-open if you can replicate it again
