### ISSUE TITLE
typing error: computed

### ISSUE THREAD

**Issue by sap471** [vueuse/head#37]
i use **vue@^3.2.13** and **@vueuse/head@^0.6.0**, there is reference error while typing computed.
it's not show but i forgot what version of vue that i used before, but after i upgrade this error show up.

****

```
Type 'ComputedRef<string | undefined>' is not assignable to type 'MaybeRef<string> | undefined'.
  Type 'ComputedRef<string | undefined>' is not assignable to type 'Ref<string>'.ts(2322)
```

```
<script setup lang="ts">
import { computed } from "vue";
import { useHead } from "@vueuse/head";

const data = reactive<IMangaResult>({});

useHead({
  title: computed(() => data.title),
});
</script>
```

**Comment by websitevirtuoso** [comment]
I have the same situation why I can't use it like this
![image](https://user-images.githubusercontent.com/5112918/173213759-2be83123-6475-4853-a0d0-1e6ab48dd037.png)
