### ISSUE TITLE
Documentation does not specify where to place the "Server-side rendering"

### ISSUE THREAD

**Issue by maria-arce** [vueuse/head#40]
Hello, first at all thank you for the Document manager. Just more like a suggestion, and a question as well, also for people that never had to work with metas in the past like me, might be not aware where  and how to configure the ssr part. It's not specify, I also checked the repository looking for this part. In general will be cool to have a tutorial for this plugin because I noticed there not much information around on the web, and the places that I found where just a copy and paste from the read me file. :)

**Comment by seunafara** [comment]
Anyone found a way to do this yet?

**Comment by cookie10codes** [comment]
I'm also curious

**Comment by egoist** [comment]
there's already a simple example: https://github.com/vueuse/head#server-side-rendering

call `renderHeadToString` after `renderToString`

**Comment by harlan-zw** [comment]
Issue seems stale, going to close.

Please re-open if you're still stuck and would like some help.
