### ISSUE TITLE
feat: add suffix to all titles

### ISSUE THREAD

**Issue by privatenumber** [vueuse/head#56]
## Feature request
I'd like a way to add a suffix to all titles automatically.

In my use-case, every title from my site should be suffixed with the website name:
- `Home | privatenumber`
- `Blog | privatenumber`
- `Contact | privatenumber`

## Technical approach

I'm wondering if it would make sense to add an API to `createHead()`:
```js
const head = createHead({
    title: (titleValue) => titleValue + ' | privatenumber'
})

app.use(head)
```

**Comment by harlan-zw** [comment]
This issue looks resolved as `titleTemplate` supports this functionality: https://github.com/vueuse/head/pull/49/files, going to close it.
