### ISSUE TITLE
dynamic data for title fetched by created()

### ISSUE THREAD

**Issue by thehatami** [vueuse/head#57]
how can i set my title after data fetched by created() in vue3. my structure is:
```
data () {
    return {
      article: null,
    }
  },
setup() {
    const siteData = reactive({
      title: this.article.title
    })

    useHead({
      title: computed(() => _title??_)
    })
  },
async created () {
 query({})
.then () = {
this.article = data.articleByID
}
}
```

**Comment by harlan-zw** [comment]
Within the v1 RC's, the following should work fine:

```ts
useHead({
  title: () => article?.title
})
```

Note that in your code you're using `this` within `setup` which isn't supported. (see https://vuejs.org/api/composition-api-setup.html#basic-usage)

You will either need to load the article in the `setup` function or use the `Head` component.
