### ISSUE TITLE
<Head> component with v-html directive

### ISSUE THREAD

**Issue by yakir-reznik** [vueuse/head#63]
Hello.
I'm using RankMath - a well known WordPress SEO plugin.
The plugin gives me a string that contains all the html that needs to go in the <head> section of the page.
e.g "<title>some title</title>".
As i mentioned the data im getting from the plugin is a string of html elements.
When i try to pass the string to the <Head> component like so:
<Head v-html="headString" />

It doesn't work. Anyway to fix this? Or some other way to achieve the desired result?

**Comment by harlan-zw** [comment]
Can you please provide a proper reproduction?

Thanks

**Comment by harlan-zw** [comment]
Closing as this issue as it's stale, please provide a reproduction to re-open.
