### ISSUE TITLE
de-duplicate `<link rel="canonical">`

### ISSUE THREAD

**Issue by danielroe** [vueuse/head#64]
similar to https://github.com/vueuse/head/issues/32, we can deduplicate canonical links....

**Comment by ririen** [comment]
Is there any way around it? It causes quite a lot of problems ...

**Comment by kakajansh** [comment]
> Is there any way around it? It causes quite a lot of problems ...

Could you find a way?

**Comment by harlan-zw** [comment]
This is resolved https://github.com/vueuse/head/commit/200f1ca1417a13a265bee45289a84ad31cf87d2b
