### ISSUE TITLE
useHead in Options API component

### ISSUE THREAD

**Issue by fallemand** [vueuse/head#68]
Can this be used in an Options API component? Is there any other way to call it than using the setup function?
Thanks.

**Comment by simeon-petrov-5** [comment]
In the description they state `@vueuse/head is a Vue composition API`, which means that the plugin supports/uses only the Composition API, a.k.a. `setup()` or `<script setup>`. 

You can still use plugins for the Composition API inside your classic Options API, like described here in [Composition API: setup() - Basic usage](https://vuejs.org/api/composition-api-setup.html#basic-usage), with the limitation that the Options API can use the return value of the Composition API (`setup()`), but not the other way around. 

Alternatively you can try to use the [Head](https://github.com/vueuse/head#head) component, which **probably** can work with the values of the Options API.

**Comment by harlan-zw** [comment]
v1 will support the Options API in Vue 2 and Vue 3 out of the box

You can try it out now https://github.com/vueuse/head/tree/v1

Will close once this it's released as stable.

**Comment by harlan-zw** [comment]
Options API doc is here: https://unhead.harlanzw.com/integrations/vue/options-api

Just replace @unhead/vue with @vueuse/head
