### ISSUE TITLE
How to get Head?

### ISSUE THREAD

**Issue by shtse8** [vueuse/head#74]
I am working on a SSR sharing plugin so that the title is generated on server side.
the case is setting head in one component while getting head on another component.
How can I achieve that?

I can get the title with this. 
```
useNuxtApp().vueApp.config.globalProperties.$head.headTags.filter(x => x.tag === 'title').filter(x => x.tag === 'title').reverse()[0].props.children
```
Any simpler way to get it?

**Comment by shtse8** [comment]
found it
```ts
const head = injectHead()
const headTags = head.headTags
```

**Comment by nadirabbas** [comment]
@shtse8 Thanks!
