### ISSUE TITLE
Watchable head

### ISSUE THREAD

**Issue by shtse8** [vueuse/head#76]
I want to watch the head and get the field if it changes.
could you expose the reactive `getTags` or emit some events on adding/removing tag and values change?
Thanks.

**Comment by harlan-zw** [comment]
Hey @shtse8 

Within the v1 RC's, you have access to hooks that let you modify resolved tags before the DOM / SSR is renderered.

```ts
const head = createHead()

head.hooks['resolved:tags'].push((tags) => {
   // do something with them
   console.log(tags) 
})
``` 

You can see a live example here: https://github.com/harlan-zw/nuxt-hedge/blob/main/src/runtime/plugin.ts#L45

Will close as this should solve your issue, let me know if you have any questions or issues though.
