### ISSUE TITLE
Question: how to prioritize some link tags above others

### ISSUE THREAD

**Issue by drwpow** [vueuse/head#86]
I’m looking to add a `<link rel="preconnect">` tag as the first item to my `<head>`, and ensure it comes before other `link` and `script` tags. Is there a way to order the tags so that this is possible? Thanks!

**Comment by harlan-zw** [comment]
Hey @drwpow 

If you're SSR, then you can may use of the new prop https://github.com/vueuse/head#render-priority

Will close this off as resolved, but feel free to re-open if you have any issues
