### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by justinthomasonline** [vueuse/head#92]
I am getting an error 'Uncaught ReferenceError: require is not defined'. at ./node_modules/@vueuse/head/dist/index.mjs (index.mjs:3:1)

![vueusehead](https://user-images.githubusercontent.com/7472517/190707391-9fd1b674-7e71-4798-8c85-8f8f995f8b04.png)

Appreciate any help

**Comment by harlan-zw** [comment]
Hey @justinthomasonline 

Could you provide some details on your implementation or ideally a reproduction repo?

**Comment by harlan-zw** [comment]
I'm happy to help but will need some way to reproduce the error so I can push out a fix

**Comment by harlan-zw** [comment]
Closing as this seems stale, please re-open with a reproduction if you'd like some help.
